Profile readme
partiql/.github pull request #1
Opened 2023-11-30 18:54 UTC by yliuuuu

*Issue #, if available:* N/A

*Description of changes:*
Organization readme.  

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-30 18:58 UTC, RCHowell requested changes

2023-11-30 18:58 UTC, RCHowell commented on profile/README.md
> +PartiQL is an expressive, SQL-compatible query language giving access to relational, semi-structured, and nested data. PartiQL is Open Sourced under PartiQL is open-sourced under the Apache 2.0 Licen
```suggestion
PartiQL is an expressive, SQL-compatible query language giving access to relational, semi-structured, and nested data. PartiQL is open sourced under the Apache 2.0 License. 
```

2023-11-30 18:58 UTC, RCHowell commented on profile/README.md
> +* If you have questions or ideas towards PartiQL as a Language, check out our [GitHub Discussion](https://github.com/orgs/partiql/discussions) forum.
```suggestion
* If you have questions or suggestions about the PartiQL Language, please check out our [GitHub Discussion](https://github.com/orgs/partiql/discussions) forum.
```

2023-11-30 18:58 UTC, RCHowell commented on profile/README.md
> +* Check out the [CONTRIBUTING.md](../CONTRIBUTING.md) file to learn how to contribute.
```suggestion
* Please see the [CONTRIBUTING.md](../CONTRIBUTING.md) file to learn how to contribute.
```

2023-11-30 19:06 UTC, rchowell requested changes

2023-11-30 19:06 UTC, rchowell commented on profile/README.md
> +        <img src="PartiQL_Logo_Dark.svg" alt="PartiQL Logo" width="300" height="300">
```suggestion
        <img src="PartiQL_Logo_Dark.svg" alt="PartiQL Logo" width="100" height="100">
```

Just a preference, but it looks a bit big when rendered

2023-11-30 19:20 UTC, RCHowell approved these changes

2023-11-30 20:33 UTC, jpschorr commented on profile/README.md
> +PartiQL is an expressive, SQL-compatible query language giving access to relational, semi-structured, and nested data. PartiQL is open sourced under the Apache 2.0 License.
PartiQL code, including reference implementations, is Apache 2.
But the language spec is Licensed a bit differently: https://github.com/partiql/partiql-lang/blob/main/LICENSE

2023-11-30 20:42 UTC, yliuuuu commented on profile/README.md
> +PartiQL is an expressive, SQL-compatible query language giving access to relational, semi-structured, and nested data. PartiQL is open sourced under the Apache 2.0 License.
```suggestion
PartiQL is an expressive, SQL-compatible query language giving access to relational, semi-structured, and nested data. 

PartiQL code, including the reference implementations, is open sourced under the Apache 2.0 License. 
```

2023-11-30 20:42 UTC, yliuuuu commented on profile/README.md
> +* Please see the [CONTRIBUTING.md](../CONTRIBUTING.md) file to learn how to contribute.
```suggestion
* If you have questions or suggestions about the PartiQL Language, please check out our [GitHub Discussion](https://github.com/orgs/partiql/discussions) forum.
* If you want to contribute to the language specification, please check out our [RFC process](https://github.com/partiql/partiql-lang/blob/main/RFC-template.adoc). 
* Please see the [CONTRIBUTING.md](../CONTRIBUTING.md) file to learn how to contribute to our reference implementations.
```

2023-11-30 20:43 UTC, yliuuuu commented on profile/README.md
> +PartiQL is an expressive, SQL-compatible query language giving access to relational, semi-structured, and nested data. PartiQL is open sourced under the Apache 2.0 License.
How you like the purposed changes?

2023-12-01 21:59 UTC, RCHowell commented on profile/README.md
> +PartiQL is an expressive, SQL-compatible query language giving access to relational, semi-structured, and nested data. PartiQL is open sourced under the Apache 2.0 License.
I recommend just leaving the last sentence out at the moment.

```suggestion
PartiQL is an expressive, SQL-compatible query language giving access to relational, semi-structured, and nested data.
```

2023-12-01 22:20 UTC, merged